apiVersion: apps/v1
kind: Deployment
metadata:
  name: nf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nf
  template:
    metadata:
      labels:
        app: nf
    spec:
      containers:
        - name: nf
          image: iatethepies/newsfetcher:v10
