# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  registryConnection: 'DockerHub'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    command: 'build'
    Dockerfile: '**/allthenews_v2/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: '**/allthenews_v2/allthenews'
    command: 'push'